
server:
 port: 9001
 
 
#mysql server url username and password and application name and zipkin server url id 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: DEPARTMENT-SERVICE 
#  zipkin:
#   base-url: http://localhost:9411/  
    
#eurka client settings
#eureka:
# client:
#  register-with-eureka: true
#  fetch-registry: true
#  service-url:
#   defaultZone: http://localhost:8761/eureka/
# instance:
#  hostname: localhost      
  
  
#Redis properties
    cache:
        type: redis
    redis:
        host: redis_host
        password: redis_password
        port: 6379  
  
  
  